In [1]:
import pandas as pd
import numpy as np
import pandas as pd
from sklearn.manifold import TSNE
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import style
from rake_nltk import Rake
style.use('dark_background')

In [2]:
data=pd.read_csv("C:\\Users\\Aakash\\Desktop\\Projects\\IMDB.csv")
df=pd.DataFrame(data)

In [3]:
df.head()

,Unnamed: 0,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,...,tomatoConsensus,tomatoUserMeter,tomatoUserRating,tomatoUserReviews,tomatoURL,DVD,BoxOffice,Production,Website,Response
0,1,Hugo,2011,PG,23 Nov 2011,126 min,"Adventure, Drama, Family",Martin Scorsese,"John Logan (screenplay), Brian Selznick (book)","Ben Kingsley, Sacha Baron Cohen, Asa Butterfie...",...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/hugo/,28 Feb 2012,"$73,820,094",Paramount Studios,http://www.hugomovie.com/,True
1,2,Hugo,2011,PG,23 Nov 2011,126 min,"Adventure, Drama, Family",Martin Scorsese,"John Logan (screenplay), Brian Selznick (book)","Ben Kingsley, Sacha Baron Cohen, Asa Butterfie...",...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/hugo/,28 Feb 2012,"$73,820,094",Paramount Studios,http://www.hugomovie.com/,True
2,3,Jupiter Ascending,2015,PG-13,06 Feb 2015,127 min,"Action, Adventure, Sci-Fi","Lana Wachowski, Lilly Wachowski","Lilly Wachowski, Lana Wachowski","Mila Kunis, Channing Tatum, Sean Bean, Eddie R...",...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/jupiter_ascend...,02 Jun 2015,"$43,733,037",Warner Bros. Pictures,http://www.jupiterascending.com/,True
3,4,X-Men: Apocalypse,2016,PG-13,27 May 2016,144 min,"Action, Adventure, Sci-Fi",Bryan Singer,"Simon Kinberg (screenplay), Bryan Singer (stor...","James McAvoy, Michael Fassbender, Jennifer Law...",...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/x_men_apocalypse/,04 Oct 2016,"$135,729,385",20th Century Fox,https://www.facebook.com/xmenmovies,True
4,5,Edge of Tomorrow,2014,PG-13,06 Jun 2014,113 min,"Action, Adventure, Sci-Fi",Doug Liman,"Christopher McQuarrie (screenplay), Jez Butter...","Tom Cruise, Emily Blunt, Brendan Gleeson, Bill...",...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/live_die_repea...,07 Oct 2014,"$77,121,429",Warner Bros. Pictures,http://www.edgeoftomorrowmovie.com,True

In [4]:

#dropping columns
l=['tomatoMeter','Released','Response','BoxOffice','DVD','Rated','imdbID','Type','Website','Ratings.Source','Ratings.Value','tomatoURL','Poster','tomatoImage','Awards','tomatoRating','tomatoReviews','tomatoFresh','tomatoRotten','Website','Metascore','tomatoConsensus','tomatoUserMeter','tomatoUserRating','tomatoUserReviews']
df=df.drop(columns=l,axis=1)

df.isnull().sum()

Unnamed: 0      0
Title           0
Year            0
Runtime        15
Genre           2
Director        1
Writer         50
Actors          7
Plot           11
Language        9
Country         2
imdbRating      0
imdbVotes       0
Production    227
dtype: int64

In [5]:
#replacing nan values with 0 in case of numbers and '' for others,removing extra characters from runtime and boxoffice and converting to int

df["Runtime"]=df["Runtime"].str.extract('(^\d*)')
#df['BoxOffice']=df['BoxOffice'].str.extract('(^\d*)')
#df['Imdbrating']=df['Imdbrating']
#df["Runtime"] = df["Runtime"].str.rstrip('hmin')
df["Runtime"].fillna('0',inplace=True)
#df['BoxOffice'].fillna('0',inplace=True)
df.fillna('',inplace=True)

df["Runtime"]=df["Runtime"].astype('int64')
df["Runtime"]=df["Runtime"].astype('int64')

In [6]:
df[['Director',"Runtime",'Actors']]

,Director,Runtime,Actors
0,Martin Scorsese,126,"Ben Kingsley, Sacha Baron Cohen, Asa Butterfie..."
1,Martin Scorsese,126,"Ben Kingsley, Sacha Baron Cohen, Asa Butterfie..."
2,"Lana Wachowski, Lilly Wachowski",127,"Mila Kunis, Channing Tatum, Sean Bean, Eddie R..."
3,Bryan Singer,144,"James McAvoy, Michael Fassbender, Jennifer Law..."
4,Doug Liman,113,"Tom Cruise, Emily Blunt, Brendan Gleeson, Bill..."
...,...,...,...
4843,Maysoon Pachachi,88,
4844,Scott Smith,87,"Eric Mabius, Kristin Booth, Crystal Lowe, Geof..."
4845,Daniel Hsia,100,"Le Geng, Daniel Henney, Sean Gallagher, Bill M..."
4846,"Benjamin Roberds, Jordan Reyes",76,"Eva Boehnke, David Chandler, Maxwell Moody"
4847,"Jon Gunn, Brian Herzlinger, Brett Winn",90,"Drew Barrymore, John August, Stephanie Bedell ..."

In [7]:
df.head()

,Unnamed: 0,Title,Year,Runtime,Genre,Director,Writer,Actors,Plot,Language,Country,imdbRating,imdbVotes,Production
0,1,Hugo,2011,126,"Adventure, Drama, Family",Martin Scorsese,"John Logan (screenplay), Brian Selznick (book)","Ben Kingsley, Sacha Baron Cohen, Asa Butterfie...","In Paris in 1931, an orphan named Hugo Cabret ...",English,USA,7.5,"260,429",Paramount Studios
1,2,Hugo,2011,126,"Adventure, Drama, Family",Martin Scorsese,"John Logan (screenplay), Brian Selznick (book)","Ben Kingsley, Sacha Baron Cohen, Asa Butterfie...","In Paris in 1931, an orphan named Hugo Cabret ...",English,USA,7.5,"260,429",Paramount Studios
2,3,Jupiter Ascending,2015,127,"Action, Adventure, Sci-Fi","Lana Wachowski, Lilly Wachowski","Lilly Wachowski, Lana Wachowski","Mila Kunis, Channing Tatum, Sean Bean, Eddie R...",A young woman discovers her destiny as an heir...,"English, Russian","USA, Australia",5.3,"151,069",Warner Bros. Pictures
3,4,X-Men: Apocalypse,2016,144,"Action, Adventure, Sci-Fi",Bryan Singer,"Simon Kinberg (screenplay), Bryan Singer (stor...","James McAvoy, Michael Fassbender, Jennifer Law...",After the re-emergence of the world's first mu...,"English, Polish, German, Arabic, Egyptian (Anc...",USA,7.1,"285,476",20th Century Fox
4,5,Edge of Tomorrow,2014,113,"Action, Adventure, Sci-Fi",Doug Liman,"Christopher McQuarrie (screenplay), Jez Butter...","Tom Cruise, Emily Blunt, Brendan Gleeson, Bill...",A soldier fighting aliens gets to relive the s...,English,"USA, Canada",7.9,"475,969",Warner Bros. Pictures

In [8]:
#df['Actors'].replace('',np.nan,inplace=True)
#df['Director']=df['Director'].replace('',np.nan,inplace=True)
#df['Director']=df['Director'].dropna()
#dropping unnamed columns
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
df['Runtime']=df['Runtime'].replace(np.nan,df['Runtime'].mean(),regex=True)
df['Runtime'].value_counts()
df['Actors'].isnull().sum()

0

In [9]:
#15 colums and 4848 movies
df=df.tail(-1)#removing first row its repeated
df.head(10)
df.shape

(4847, 13)

In [10]:
# discarding the commas between the actors' full names and getting only the first three names
df['Actors'] =  [x.split(',')[:3] for x in df['Actors'] ]
df = df.fillna('missing value')
df['Genre'] = df['Genre'].map(lambda x: x.split(','))
# putting the genres in a list of words
#df['Genre'] = df['Genre'].map(lambda x: x.lower().split(','))
#df['Genre'] = [x.split(',') for x in df['Genre'] ]
df['Director'] = [x.split(',') for x in df['Director'] ]

In [11]:
# merging together first and last name for each actor and director, so it's considered as one word 
# and there is no mix up between people sharing a first name
for index, row in df.iterrows():
    df['Actors'][index] = [x.lower().replace(' ','') for x in df['Actors'][index]]
    df['Director'][index] = [x.lower().replace(' ','') for x in df['Director'][index]]

C:\Users\Aakash\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Aakash\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [12]:
df1 = df[['Title','Genre','Director','Actors','Plot']]
df1.head()

,Title,Genre,Director,Actors,Plot
1,Hugo,"[Adventure, Drama, Family]",[martinscorsese],"[benkingsley, sachabaroncohen, asabutterfield]","In Paris in 1931, an orphan named Hugo Cabret ..."
2,Jupiter Ascending,"[Action, Adventure, Sci-Fi]","[lanawachowski, lillywachowski]","[milakunis, channingtatum, seanbean]",A young woman discovers her destiny as an heir...
3,X-Men: Apocalypse,"[Action, Adventure, Sci-Fi]",[bryansinger],"[jamesmcavoy, michaelfassbender, jenniferlawre...",After the re-emergence of the world's first mu...
4,Edge of Tomorrow,"[Action, Adventure, Sci-Fi]",[dougliman],"[tomcruise, emilyblunt, brendangleeson]",A soldier fighting aliens gets to relive the s...
5,The Jungle Book,"[Adventure, Drama, Family]",[jonfavreau],"[neelsethi, billmurray, benkingsley]",After a threat from the tiger Shere Khan force...

In [13]:
#keyword extraction
#Create a empty list Keywords
df1['keywords'] = ''
#Loop across all rows to extract all keywords from description
for index, row in df1.iterrows():
    Plot = row['Plot']
 #instantiating Rake by default it uses English stopwords from NLTK and discards all punctuation chars
    r = Rake()
     #extract words by passing the text
    r.extract_keywords_from_text(Plot)
    #get the dictionary with key words and their scores
    keyword_dict_scores = r.get_word_degrees()
    #assign keywords to new columns
    row['keywords'] = list(keyword_dict_scores.keys())

C:\Users\Aakash\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [14]:

df1.head(400)

,Title,Genre,Director,Actors,Plot,keywords
1,Hugo,"[Adventure, Drama, Family]",[martinscorsese],"[benkingsley, sachabaroncohen, asabutterfield]","In Paris in 1931, an orphan named Hugo Cabret ...","[train, station, late, father, 1931, lives, pa..."
2,Jupiter Ascending,"[Action, Adventure, Sci-Fi]","[lanawachowski, lillywachowski]","[milakunis, channingtatum, seanbean]",A young woman discovers her destiny as an heir...,"[heiress, destructive, industry, young, woman,..."
3,X-Men: Apocalypse,"[Action, Adventure, Sci-Fi]",[bryansinger],"[jamesmcavoy, michaelfassbender, jenniferlawre...",After the re-emergence of the world's first mu...,"[emergence, extinction, level, plan, first, mu..."
4,Edge of Tomorrow,"[Action, Adventure, Sci-Fi]",[dougliman],"[tomcruise, emilyblunt, brendangleeson]",A soldier fighting aliens gets to relive the s...,"[soldier, fighting, aliens, gets, dies, day, r..."
5,The Jungle Book,"[Adventure, Drama, Family]",[jonfavreau],"[neelsethi, billmurray, benkingsley]",After a threat from the tiger Shere Khan force...,"[free, spirited, bear, flee, threat, man, pant..."
...,...,...,...,...,...,...
396,Cold Mountain,"[Adventure, Drama, History]",[anthonyminghella],"[judelaw, nicolekidman, renÃ©ezellweger]","In the waning days of the American Civil War, ...","[north, carolina, waning, days, wounded, soldi..."
397,The Book of Eli,"[Action, Adventure, Drama]","[alberthughes, allenhughes]","[denzelwashington, garyoldman, milakunis]","A post-apocalyptic tale, in which a lone man f...","[sacred, book, apocalyptic, tale, post, saving..."
398,Flubber,"[Comedy, Family, Sci-Fi]",[lesmayfield],"[robinwilliams, marciagayharden, christophermc...","An absent-minded professor discovers ""flubber,...","[minded, professor, discovers, absent, flubber..."
399,The Haunting,"[Fantasy, Horror, Mystery]",[jandebont],"[liamneeson, catherinezeta-jones, owenwilson]","When Eleanor, Theo, and Luke decide to take pa...","[house, marrow, tells, ghostly, past, get, sle..."
400,Space Jam,"[Animation, Adventure, Comedy]",[joepytka],"[michaeljordan, wayneknight, theresarandle]",In a desperate attempt to win a basketball mat...,"[basketball, match, earn, michael, jordan, aid..."

In [15]:
df1['bow'] = ''
columns = df1.columns
for index, row in df1.iterrows():
    words = ''
    for col in columns:
        if col!='Title':
            words = words + ' '.join(row[col])+' '
            row['bow'] = words
        else:
            words=words+row[col]+' '
        
#df1.drop([col for col in df1.columns if col!= 'bow'], axis = 1, inplace = True)
#Use below code if you do not want to include director name into bow
    #for col in columns:
        #if col != 'director':
            #words = words + ' '.join(row[col])+ ' '
        #else:
            #words = words + row[col]+ ' '
        #row['bow'] = words

    
#df1.drop(columns = [col for col in df1.columns if col!= 'bag_of_words'], inplace = True)

C:\Users\Aakash\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [16]:
df1['bow']

1       Hugo Adventure  Drama  Family martinscorsese b...
2       Jupiter Ascending Action  Adventure  Sci-Fi la...
3       X-Men: Apocalypse Action  Adventure  Sci-Fi br...
4       Edge of Tomorrow Action  Adventure  Sci-Fi dou...
5       The Jungle Book Adventure  Drama  Family jonfa...
                              ...
4843    Return to the Land of Wonders Documentary  War...
4844    Signed Sealed Delivered Comedy  Drama scottsmi...
4845    Shanghai Calling Comedy  Drama  Romance daniel...
4846    A Plague So Pleasant Drama  Horror  Thriller b...
4847    My Date with Drew Documentary jongunn brianher...
Name: bow, Length: 4847, dtype: object

In [17]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer #tokenizes a collection of words extracted from a text doc
from ast import literal_eval #This evaluates whether an expresion is a Python datatype or not
#count vectorizer
#igenerating the count matrix
#instantiating and generating the count matrix
count = CountVectorizer()
tfidf= TfidfVectorizer()
count_matrix = count.fit_transform(df1['bow'])
count_matrix_tfidf=tfidf.fit_transform(df1['bow'])
#create a Series for movie titles so they are associated to an ordered numerical list, we will use this later to match index
indices = pd.Series(df1.iloc[:,0],df1.index)
indices

1                                Hugo
2                   Jupiter Ascending
3                   X-Men: Apocalypse
4                    Edge of Tomorrow
5                     The Jungle Book
                    ...
4843    Return to the Land of Wonders
4844          Signed Sealed Delivered
4845                 Shanghai Calling
4846             A Plague So Pleasant
4847                My Date with Drew
Name: Title, Length: 4847, dtype: object

In [18]:
(count_matrix)

<4847x24702 sparse matrix of type '<class 'numpy.int64'>'
	with 115857 stored elements in Compressed Sparse Row format>

In [19]:
#Convert sparse count_matrix to dense vector
c = count_matrix.todense()
c

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
#Print count_matrix for 0th row
#print(count_matrix[0,:]) #This shows all words and their frequency in bow of 0th row
#print(count_matrix_tfidf[0,:])

In [21]:
#Gives vocabulary of all words in 'bow' and their counts
count.vocabulary_

{'hugo': 10256,
 'adventure': 568,
 'drama': 6713,
 'family': 7920,
 'martinscorsese': 14426,
 'benkingsley': 2372,
 'sachabaroncohen': 19641,
 'asabutterfield': 1687,
 'train': 22864,
 'station': 21269,
 'late': 13133,
 'father': 7972,
 '1931': 95,
 'lives': 13593,
 'paris': 16781,
 'orphan': 16532,
 'named': 15722,
 'cabret': 3342,
 'mystery': 15686,
 'involving': 10862,
 'walls': 23916,
 'wrapped': 24431,
 'automaton': 1886,
 'jupiter': 12342,
 'ascending': 1690,
 'action': 419,
 'sci': 19956,
 'fi': 8089,
 'lanawachowski': 13058,
 'lillywachowski': 13487,
 'milakunis': 15180,
 'channingtatum': 3826,
 'seanbean': 20070,
 'heiress': 9831,
 'destructive': 6138,
 'industry': 10592,
 'young': 24548,
 'woman': 24354,
 'discovers': 6359,
 'inhabitants': 10649,
 'ancient': 1148,
 'must': 15657,
 'fight': 8114,
 'destiny': 6129,
 'protect': 17934,
 'earth': 6921,
 'intergalactic': 10767,
 'nobility': 16132,
 'men': 14812,
 'apocalypse': 1481,
 'bryansinger': 3187,
 'jamesmcavoy': 11153,
 'michaelfassbender': 14946,
 'jenniferlawrence': 11474,
 'emergence': 7229,
 'extinction': 7824,
 'level': 13404,
 'plan': 17469,
 'first': 8184,
 'mutant': 15660,
 'unite': 23344,
 'world': 24411,
 'destroyer': 6132,
 'defeat': 5906,
 'edge': 6975,
 'of': 16325,
 'tomorrow': 22688,
 'dougliman': 6675,
 'tomcruise': 22645,
 'emilyblunt': 7251,
 'brendangleeson': 2983,
 'soldier': 20905,
 'fighting': 8117,
 'aliens': 908,
 'gets': 8986,
 'dies': 6262,
 'day': 5761,
 'restarting': 18779,
 'every': 7680,
 'time': 22517,
 'relive': 18621,
 'the': 22316,
 'jungle': 12331,
 'book': 2788,
 'jonfavreau': 12064,
 'neelsethi': 15880,
 'billmurray': 2520,
 'free': 8554,
 'spirited': 21105,
 'bear': 2212,
 'flee': 8234,
 'threat': 22425,
 'man': 14102,
 'panther': 16747,
 'tiger': 22489,
 'shere': 20459,
 'khan': 12745,
 'forces': 8341,
 'self': 20167,
 'discovery': 6360,
 'bagheera': 2007,
 'help': 9862,
 'journey': 12207,
 'cub': 5220,
 'mowgli': 15576,
 'embarks': 7213,
 'baloo': 2038,
 'inside': 10697,
 'out': 16573,
 'animation': 1301,
 'comedy': 4588,
 'petedocter': 17185,
 'ronniedelcarmen': 19390,
 'amypoehler': 1113,
 'phyllissmith': 17347,
 'richardkind': 18940,
 'midwest': 15115,
 'life': 13456,
 'emotions': 7300,
 'navigate': 15832,
 'house': 10182,
 'joy': 12212,
 'disgust': 6376,
 'conflict': 4737,
 'anger': 1274,
 'san': 19771,
 'francisco': 8440,
 'school': 19945,
 'uprooted': 23445,
 'moved': 15569,
 'best': 2432,
 'fear': 7992,
 'riley': 19048,
 'sadness': 19658,
 'new': 15952,
 'city': 4290,
 'up': 23430,
 'bobpeterson': 2726,
 'edwardasner': 7013,
 'christopherplummer': 4206,
 'jordannagai': 12100,
 'inadvertently': 10521,
 'taking': 21991,
 'eight': 7055,
 'year': 24517,
 'old': 16354,
 'carl': 3529,
 'fredricksen': 8544,
 'travels': 22935,
 'seventy': 20283,
 'home': 10077,
 'equipped': 7455,
 'balloons': 2036,
 'stowaway': 21516,
 'paradise': 16762,
 'falls': 7911,
 'monsters': 15451,
 'vs': 23858,
 'robletterman': 19243,
 'conradvernon': 4791,
 'reesewitherspoon': 18514,
 'sethrogen': 20266,
 'hughlaurie': 10252,
 'sent': 20207,
 'transformed': 22894,
 'government': 9202,
 'take': 21982,
 'alien': 905,
 'mastermind': 14491,
 'trying': 23070,
 'team': 22127,
 'struck': 21583,
 'giant': 9007,
 'meteorite': 14863,
 'wedding': 24060,
 'becomes': 2249,
 'part': 16799,
 'suicide': 21700,
 'squad': 21168,
 'fantasy': 7939,
 'davidayer': 5619,
 'willsmith': 24260,
 'jaimefitzsimons': 11060,
 'ikebarinholtz': 10420,
 'form': 8367,
 'villains': 23722,
 'secret': 20119,
 'agency': 626,
 'recruits': 18480,
 'save': 19890,
 'mission': 15311,
 'defensive': 5923,
 'task': 22076,
 'force': 8338,
 'dangerous': 5410,
 'incarcerated': 10525,
 'super': 21740,
 'joe': 11723,
 'rise': 19069,
 'cobra': 4461,
 'stephensommers': 21365,
 'adewaleakinnuoye': 499,
 'agbaje': 621,
 'christophereccleston': 4177,
 'grÃ©goryfitoussi': 9407,
 'elite': 7133,
 'military': 15197,
 'unit': 23343,
 'comprised': 4677,
 'evil': 7692,
 'organization': 16508,
 'led': 13262,
 'operating': 16453,
 'pit': 17434,
 'takes': 21988,
 'notorious': 16211,
 'arms': 1620,
 'dealer': 5791,
 'special': 21048,
 'operatives': 16459,
 'known': 12888,
 'wild': 24178,
 'west': 24106,
 'barrysonnenfeld': 2149,
 'kevinkline': 12711,
 'kennethbranagh': 12658,
 'villain': 23720,
 'century': 3771,
 'inventor': 10835,
 'nineteenth': 16102,
 'two': 23150,
 'hired': 9992,
 'guns': 9469,
 'president': 17771,
 'grant': 9260,
 'clutches': 4442,
 'mummy': 15607,
 'tomb': 22632,
 'dragon': 6701,
 'emperor': 7303,
 'robcohen': 19133,
 'brendanfraser': 2982,
 'jetli': 11594,
 'mariabello': 14228,
 'qin': 18059,
 'far': 7940,
 'east': 6927,
 'shape': 20361,
 'witch': 24320,
 'centuries': 3769,
 'ago': 641,
 'connell': 4768,
 'alex': 801,
 'unearths': 23297,
 'shifting': 20476,
 'entity': 7418,
 'cursed': 5268,
 'evy': 7698,
 'famed': 7915,
 'fighters': 8116,
 'rick': 18989,
 'son': 20940,
 'evan': 7645,
 'almighty': 972,
 'tomshadyac': 22700,
 'stevecarell': 21400,
 'morganfreeman': 15496,
 'laurengraham': 13187,
 'preparation': 17750,
 'great': 9283,
 'flood': 8265,
 'build': 3220,
 'ark': 1596,
 'tells': 22180,
 'god': 9127,
 'contacts': 4827,
 'congressman': 4754,
 'baxter': 2197,
 'waterworld': 24017,
 'kevinreynolds': 12724,
 'kevincostner': 12698,
 'chaimjeraffi': 3787,
 'rickaviles': 18990,
 'almost': 973,
 'entirely': 7415,
 'submerged': 21651,
 'outlaw': 16586,
 'reluctantly': 18628,
 'helps': 9867,
 'smokers': 20822,
 'future': 8660,
 'girl': 9055,
 'try': 23068,
 'melted': 14793,
 'find': 8146,
 'dry': 6791,
 'land': 13070,
 'caps': 3482,
 'polar': 17567,
 'ice': 10368,
 'mutated': 15662,
 'mariner': 14266,
 'fights': 8118,
 'starvation': 21261,
 '47': 236,
 'ronin': 19384,
 'carlrinsch': 3555,
 'keanureeves': 12581,
 'hiroyukisanada': 9999,
 'koshibasaki': 12907,
 'master': 14489,
 'ruthless': 19593,
 'shogun': 20511,
 'death': 5808,
 'dishonor': 6379,
 'band': 2050,
 'avenge': 1899,
 'hands': 9580,
 'samurai': 19766,
 'set': 20259,
 'traveller': 22933,
 'romance': 19349,
 'rolandjoffÃ©': 19336,
 'joshhartnett': 12160,
 'bipashabasu': 2567,
 'tamsinegerton': 22026,
 'riveting': 19100,
 'tale': 21995,
 'impossible': 10500,
 'love': 13777,
 'across': 416,
 'periods': 17137,
 'continents': 4850,
 'sweeping': 21884,
 'epic': 7440,
 'guardians': 9418,
 'galaxy': 8716,
 'jamesgunn': 11134,
 'chrispratt': 4100,
 'zoesaldana': 24659,
 'davebautista': 5590,
 'group': 9388,
 'fanatical': 7926,
 'warrior': 23983,
 'control': 4866,
 'universe': 23349,
 'work': 24402,
 'together': 22617,
 'forced': 8339,
 'criminals': 5137,
 'stop': 21504,
 'iron': 10895,
 'robertdowneyjr': 19162,
 'gwynethpaltrow': 9494,
 'doncheadle': 6573,
 'ties': 22483,
 'identity': 10389,
 'vengeful': 23593,
 'mad': 13961,
 'tony': 22718,
 'stark': 21246,
 'contend': 4839,
 'aware': 1930,
 'declining': 5875,
 'health': 9772,
 'legacy': 13291,
 'captain': 3487,
 'america': 1059,
 'winter': 24302,
 'anthonyrusso': 1425,
 'joerusso': 11773,
 'chrisevans': 4071,
 'samuell': 19764,
 'jackson': 11017,
 'scarlettjohansson': 19920,
 'role': 19338,
 'agent': 629,
 'battle': 2188,
 'history': 10007,
 'steve': 21389,
 'rogers': 19322,
 'struggles': 21588,
 'embrace': 7222,
 'fellow': 8041,
 'avenger': 1900,
 'modern': 15373,
 'black': 2591,
 'widow': 24167,
 'assassin': 1740,
 'teams': 22132,
 'dawn': 5758,
 'planet': 17473,
 'apes': 1479,
 'mattreeves': 14593,
 'andyserkis': 1250,
 'jasonclarke': 11272,
 'garyoldman': 8791,
 'human': 10263,
 'survivors': 21823,
 'genetically': 8871,
 'evolved': 7696,
 'caesar': 3354,
 'growing': 9396,
 'nation': 15807,
 'decade': 5842,
 'earlier': 6912,
 'devastating': 6166,
 'virus': 23786,
 'unleashed': 23359,
 'threatened': 22427,
 'express': 7815,
 'robertzemeckis': 19227,
 'tomhanks': 22658,
 'lesliezemeckis': 13386,
 'eddiedeezen': 6957,
 'bravery': 2944,
 'learns': 13247,
 'north': 16185,
 'pole': 17570,
 'christmas': 4158,
 'boy': 2868,
 'friendship': 8590,
 'spirit': 21104,
 'magical': 14014,
 'snow': 20858,
 'white': 24143,
 'and': 1149,
 'huntsman': 10299,
 'rupertsanders': 19557,
 'kristenstewart': 12933,
 'chrishemsworth': 4076,
 'charlizetheron': 3889,
 'becoming': 2250,
 'mentor': 14826,
 'fairy': 7894,
 'quest': 18087,
 'queen': 18080,
 'ordered': 16498,
 'killed': 12778,
 'winds': 24281,
 'twist': 23142,
 'vanquish': 23555,
 'protector': 17939,
 'woods': 24381,
 'terminator': 22246,
 'machines': 13944,
 'jonathanmostow': 12043,
 'arnoldschwarzenegger': 1627,
 'nickstahl': 16026,
 'clairedanes': 4305,
 'apocalyptic': 1482,
 'back': 1977,
 'post': 17666,
 'cybernetic': 5296,
 'advanced': 565,
 'robotic': 19251,
 'ensure': 7400,
 '25': 206,
 'drifter': 6751,
 'wife': 24174,
 'survive': 21818,
 'nuclear': 16229,
 'attack': 1806,
 'tomorrowland': 22689,
 'bradbird': 2881,
 'georgeclooney': 8917,
 'brittrobertson': 3100,
 'exists': 7748,
 'scientific': 19958,
 'curiosity': 5256,
 'secrets': 20125,
 'shared': 20367,
 'former': 8369,
 'space': 21010,
 'teen': 22156,
 'bursting': 3273,
 'genius': 8881,
 'embark': 7211,
 'unearth': 23296,
 'collective': 4529,
 'memory': 14810,
 'bound': 2846,
 'place': 17455,
 'somewhere': 20938,
 'alice': 888,
 'through': 22443,
 'looking': 13687,
 'glass': 9083,
 'jamesbobin': 11099,
 'johnnydepp': 11930,
 'miawasikowska': 14888,
 'helenabonhamcarter': 9839,
 'hatter': 9727,
 'whimsical': 24130,
 'returns': 18823,
 'wonderland': 24364,
 'shrek': 20554,
 'forever': 8357,
 'after': 611,
 'mikemitchell': 15166,
 'mikemyers': 15167,
 'eddiemurphy': 6964,
 'camerondiaz': 3413,
 'rumpelstiltskin': 19538,
 'tricks': 22994,
 'rumpel': 19537,
 'rules': 19525,
 'supreme': 21783,
 'erased': 7462,
 'mid': 15103,
 'cast': 3657,
 'crisis': 5143,
 'burdened': 3245,
 'existence': 7745,
 'allowing': 964,
 'dark': 5530,
 'alternate': 994,
 'timeline': 22523,
 'big': 2482,
 'hero': 9921,
 'donhall': 6581,
 'chriswilliams': 4225,
 'scottadsit': 19981,
 'ryanpotter': 19618,
 'danielhenney': 5439,
 'friends': 8589,
 'tech': 22139,
 'heroes': 9922,
 'prodigy': 17851,
 'hiro': 9995,
 'hamada': 9557,
 'develops': 6175,
 'sized': 20715,
 'inflatable': 10621,
 'robot': 19250,
 'baymax': 2200,
 'high': 9954,
 'bond': 2765,
 'plus': 17537,
 'how': 10196,
 'to': 22590,
 'your': 24552,
 'deandeblois': 5798,
 'chrissanders': 4105,
 'jaybaruchel': 11333,
 'gerardbutler': 8962,
 'craigferguson': 5070,
 'hunt': 10291,
 'dragons': 6705,
 'unlikely': 23364,
 'friend': 8586,
 'creatures': 5111,
 'assumed': 1769,
 'aspires': 1735,
 'may': 14656,
 'hapless': 9610,
 'viking': 23713,
 'wreck': 24436,
 'it': 10944,
 'ralph': 18214,
 'richmoore': 18988,
 'johnc': 11825,
 'reilly': 18581,
 'sarahsilverman': 19839,
 'jackmcbrayer': 11006,
 'dream': 6729,
 'whole': 24154,
 'arcade': 1543,
 'video': 23688,
 'game': 8736,
 'wants': 23947,
 'sets': 20268,
 'fulfill': 8629,
 'brings': 3081,
 'havoc': 9741,
 'interstellar': 10793,
 'christophernolan': 4205,
 'ellenburstyn': 7170,
 'matthewmcconaughey': 14562,
 'mackenziefoy': 13949,
 'wormhole': 24415,
 'explorers': 7803,
 'travel': 22929,
 'survival': 21816,
 'attempt': 1811,
 'humanity': 10264,
 'independence': 10564,
 'resurgence': 18798,
 'rolandemmerich': 19335,
 'liamhemsworth': 13433,
 'jeffgoldblum': 11406,
 'jessiet': 11582,
 'usher': 23477,
 'decades': 5844,
 'mankind': 14136,
 'solar': 20902,
 'faced': 7865,
 'defenses': 5922,
 'extra': 7830,
 'enough': 7381,
 'invasion': 10828,
 'third': 22370,
 'chrismiller': 4088,
 'ramanhui': 18228,
 'heir': 9830,
 'one': 16430,
 'give': 9066,
 'coup': 5014,
 'law': 13202,
 'king': 12817,
 'harold': 9660,
 'ill': 10423,
 'boots': 2803,
 'puss': 18039,
 'rebellious': 18416,
 'artie': 1672,
 'donkey': 6586,
 'beloved': 2326,
 'swamp': 21869,
 'rallies': 18212,
 'princess': 17815,
 'fiona': 8161,
 'royal': 19482,
 'girlfriends': 9057,
 'jilted': 11622,
 'prince': 17814,
 'charming': 3903,
 'fend': 8051,
 'away': 1932,
 'etat': 7599,
 'install': 10716,
 'however': 10206,
 'looked': 13686,
 'inception': 10530,
 'leonardodicaprio': 13355,
 'josephgordon': 12129,
 'levitt': 13409,
 'ellenpage': 7174,
 'thief': 22358,
 'steals': 21285,
 'corporate': 4953,
 'mind': 15226,
 'planting': 17484,
 'given': 9067,
 'idea': 10377,
 'sharing': 20371,
 'technology': 22141,
 'use': 23472,
 'inverse': 10837,
 'ceo': 3772,
 'hunger': 10288,
 'games': 8738,
 'mockingjay': 15366,
 'francislawrence': 8444,
 'joshhutcherson': 12162,
 'balance': 2024,
 'districts': 6433,
 'army': 1622,
 'bring': 3079,
 'rebellion': 18415,
 'katniss': 12548,
 'everdeen': 7672,
 'panem': 16738,
 'escalates': 7557,
 'reluctant': 18627,
 'leader': 13227,
 'destruction': 6137,
 'war': 23948,
 'holds': 10049,
 'dear': 5806,
 'hangs': 9587,
 'fast': 7958,
 'furious': 8650,
 'crime': 5131,
 'thriller': 22436,
 'paulwalker': 17020,
 'vindiesel': 23748,
 'michellerodriguez': 15073,
 'loyalty': 13795,
 'really': 18379,
 'lies': 13450,
 'undercover': 23265,
 'connor': 4774,
 'decide': 5859,
 'los': 13729,
 'angeles': 1264,
 'police': 17571,
 'officer': 16334,
 'brian': 3011,
 'destroy': 6130,
 'enamored': 7317,
 'street': 21547,
 'racing': 18150,
 'shin': 20481,
 'godzilla': 9138,
 'hideakianno': 9946,
 'shinjihiguchi': 20487,
 'crisgeorge': 5142,
 'hirokihasegawa': 9996,
 'yutakatakenouchi': 24574,
 'satomiishihara': 19874,
 'chaos': 3830,
 'upon': 23441,
 'plunged': 17534,
 'japan': 11245,
 'monster': 15450,
 'appearance': 1493,
 'class': 4327,
 'matthewvaughn': 14575,
 'laurencebelcher': 13181,
 'superhuman': 21750,
 'abilities': 329,
 '1962': 126,
 'malicious': 14081,
 'dictator': 6251,
 'start': 21256,
 'iii': 10418,
 'determined': 6149,
 'united': 23345,
 'states': 21268,
 'enlists': 7379,
 'mutants': 15661,
 'curious': 5257,
 'case': 3635,
 'benjamin': 2361,
 'button': 3310,
 'davidfincher': 5652,
 'cateblanchett': 3673,
 'bradpitt': 2898,
 'juliaormond': 12287,
 'bizarre': 2587,
 'consequences': 4796,
 'story': 21514,
 'starts': 21260,
 'aging': 636,
 'backwards': 1990,
 'sorcerer': 20974,
 'apprentice': 1513,
 'jonturteltaub': 12089,
 'nicolascage': 16038,
 'alfredmolina': 876,
 'balthazar': 2040,
 'blake': 2612,
 'sorceress': 20975,
 'morgana': 15493,
 'la': 13003,
 'fÃ©e': 8664,
 'descendant': 6084,
 'merlin': 14842,
 'poseidon': 17645,
 'wolfgangpetersen': 24350,
 'joshlucas': 12163,
 'kurtrussell': 12979,
 'jacindabarrett': 10978,
 'luxury': 13892,
 'ocean': 16303,
 'liner': 13532,
 'capsizes': 3485,
 'swamped': 21870,
 'sinking': 20687,
 'ship': 20491,
 'rogue': 19326,
 'wave': 24020,
 'escape': 7560,
 'left': 13287,
 'eve': 7658,
 'warcraft': 23950,
 'beginning': 2282,
 'duncanjones': 6835,
 'travisfimmel': 22939,
 'paulapatton': 16939,
 'benfoster': 2354,
 'orc': 16491,
 'horde': 10135,
 'invades': 10825,
 'magic': 14013,
 'portal': 17632,
 'azeroth': 1952,
 'using': 23479,
 'true': 23056,
 'behind': 2290,
 'dissenting': 6419,
 'orcs': 16495,
 'chronicles': 4233,
 'narnia': 15752,
 'voyage': 23855,
 'treader': 22945,
 'michaelapted': 14897,
 'georgiehenley': 8953,
 'skandarkeynes': 20716,
 'benbarnes': 2334,
 'edmund': 6990,
 'pevensie': 17267,
 'return': 18820,
 'encounter': 7324,
 'reaching': 18361,
 'dwarves': 6869,
 'caspian': 3650,
 'meet': 14732,
 'lost': 13738,
 'warriors': 23984,
 'cousin': 5033,
 'eustace': 7627,
 'along': 978,
 'lucy': 13827,
 'way': 24024,
 'sea': 20055,
 'aboard': 334,
 'merfolk': 14841,
 'trip': 23007,
 'genisys': 8880,
 'alantaylor': 742,
 'emiliaclarke': 7238,
 'events': 7668,
 'creates': 5104,
 'sends': 20192,
 'sgt': 20300,
 'resistance': 18754,
 '1984': 150,
 'sarah': 19815,
 'john': 11799,
 'kyle': 12989,
 'reese': 18511,
 'fractured': 8413,
 'safeguard': 19665,
 'unexpected': 23302,
 'turn': 23113,
 'alexander': 803,
 'biography': 2559,
 'oliverstone': 16383,
 'anthonyhopkins': 1411,
 'davidbedella': 5624,
 'jessiekamm': 11580,
 'greatest': 9285,
 'leaders': 13228,
 'macedonia': 13932,
 'conquers': 4783,
 'much': 15584,
 'warfare': 23956,
 'pearl': 17052,
 'harbor': 9626,
 'michaelbay': 14901,
 'benaffleck': 2333,
 'katebeckinsale': 12477,
 'mixed': 15350,
 'follows': 8319,
 'lifelong': 13459,
 '1941': 104,
 'beautiful': 2233,
 'nurse': 16245,
 'caught': 3709,
 'horror': 10148,
 'infamous': 10603,
 'sunday': 21728,
 'morning': 15510,
 'transformers': 22895,
 'shialabeouf': 20472,
 'meganfox': 14743,
 'joshduhamel': 12156,
 'cybertronian': 5297,
 'races': 18123,
 'comes': 4591,
 'teenager': 22159,
 'heroic': 9923,
 'autobots': 1881,
 'ultimate': 23208,
 'power': 17693,
 'held': 9836,
 'clue': 4437,
 'struggle': 21586,
 'decepticons': 5854,
 'frozen': 8612,
 'chrisbuck': 4054,
 'jenniferlee': 11475,
 'kristenbell': 12928,
 'idinamenzel': 10392,
 'jonathangroff': 12029,
 'snowman': 20863,
 'curse': 5267,
 'things': 22363,
 'infinite': 10620,
 'anna': 1310,
 'playful': 17498,
 'reindeer': 18585,
 'weather': 24049,
 'condition': 4709,
 'mountain': 15556,
 'sister': 20700,
 'newly': 15960,
 'crowned': 5184,
 'elsa': 7193,
 'accidentally': 374,
 'uses': 23476,
 'change': 3817,
 'harry': 9684,
 'potter': 17682,
 'order': 16497,
 'phoenix': 17331,
 'davidyates': 5751,
 'danielradcliffe': 5456,
 'harrymelling': 9696,
 'jasonboyd': 11270,
 'wizard': 24339,
 'authorities': 1874,
 'targeted': 22063,
 'hogwarts': 10041,
 'warning': 23971,
 'authoritarian': 1873,
 'bureaucrat': 3249,
 'slowly': 20802,
 'seizes': 20159,
 'lord': 13703,
 'voldemort': 23833,
 'dumbledore': 6828,
 'scoffed': 19963,
 'goblet': 9126,
 'fire': 8167,
 'mikenewell': 15169,
 'ericsykes': 7511,
 'timothyspall': 22555,
 'davidtennant': 5738,
 'finds': 8148,
 'hazard': 9755,
 'recurring': 18481,
 'nightmares': 16078,
 'distracted': 6428,
 'competing': 4647,
 'rival': 19092,
 'schools': 19952,
 'tournament': 22803,
 'matrix': 14521,
 'reloaded': 18622,
 'rayanthony': 18333,
 'christineanu': 4151,
 'andyarness': 1237,
 'fate': 7967,
 '250': 207,
 '000': 0,
 'probes': 17839,
 'discover': 6356,
 'zion': 24647,
 'neo': 15921,
 'trinity': 23005,
 'rebel': 18414,
 'estimate': 7595,
 'dreams': 6737,
 '72': 265,
 'hours': 10181,
 'am': 1014,
 'legend': 13294,
 'alicebraga': 889,
 'charlietahan': 3886,
 'transforms': 22897,
 'cure': 5251,
 'years': 24519,
 'plague': 17462,
 'kills': 12783,
 'rest': 18777,
 'york': 24542,
 'valiantly': 23517,
 'sole': 20907,
 'survivor': 21822,
 'hancock': 9570,
 'peterberg': 17192,
 'jasonbateman': 11265,
 'superhero': 21748,
 'whose': 24159,
 'considered': 4803,
 'behavior': 2288,
 'regularly': 18563,
 'causes': 3713,
 'damage': 5350,
 'public': 17990,
 'image': 10446,
 'changes': 3821,
 'millions': 15211,
 'improve': 10512,
 'person': 17161,
 'saves': 19892,
 'charlie': 3874,
 'chocolate': 4032,
 'factory': 7877,
 'timburton': 22512,
 'freddiehighmore': 8528,
 'davidkelly': 5675,
 'wins': 24297,
 'magnificent': 14021,
 'unusual': 23420,
 'candy': 3448,
 'maker': 14053,
 'tour': 22800,
 'ratatouille': 18305,
 'janpinkava': 11239,
 'pattonoswalt': 16927,
 'ianholm': 10353,
 'louromano': 13771,
 'cook': 4896,
 'makes': 14055,
 'kitchen': 12855,
 'worker': 24405,
 ...}

In [22]:
#generating the cosine similarity matrix

cosine_sim = cosine_similarity(count_matrix, count_matrix)
cosine_sim_tfidf=cosine_similarity(count_matrix_tfidf,count_matrix_tfidf)

In [23]:
def recommendations(title,n,cosine_sim = cosine_sim):
    recommended_movies = []
    recommended_movies_tfidf = []
    
    #get index of the movie that matches the title
    idx=indices[indices==title].index[0]
    
    #find highest cosine_sim this title shares with other titles extracted earlier and save it in a Series
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)
    score_series_tfidf=pd.Series(cosine_sim_tfidf[idx]).sort_values(ascending = False)
    #get indexes of the 'n' most similar movies
    top_n_indexes = list(score_series.iloc[1:n+1].index)
    top_n_indexes_tfidf = list(score_series_tfidf.iloc[1:n+1].index)
    print(top_n_indexes)
    
    #populating the list with titles of n matching movie
    for i in top_n_indexes:
        recommended_movies.append(list(indices)[i])
        recommended_movies_tfidf.append(list(indices)[i])
    return recommended_movies,recommended_movies_tfidf

In [67]:
#movie = input("Enter the movie name you wished to be recommended similar movies: ").lower()
title = 'The Prestige'
#n = int(input("How many movies do you want to be recommended: "))
n = 10

In [68]:
recommendations(title, n) #input of the prestige recommends the illusionist as well

[3057, 1808, 2171, 1646, 2411, 2588, 4661, 1285, 3306, 4081]

(['The House of Mirth',
  'The House Bunny',
  'The Quiet American',
  'Keeping the Faith',
  'The Illusionist',
  'The Love Letter',
  'The Incredibly True Adventure of Two Girls in Love',
  'Twilight',
  'Code 46',
  'Silent House'],
 ['The House of Mirth',
  'The House Bunny',
  'The Quiet American',
  'Keeping the Faith',
  'The Illusionist',
  'The Love Letter',
  'The Incredibly True Adventure of Two Girls in Love',
  'Twilight',
  'Code 46',
  'Silent House'])

In [52]:
title=indices[16]
title

'Time Traveller'

In [51]:
recommendations(title, n)

[245, 488, 3480, 166, 370, 280, 725, 1718, 4076, 2791]

(["Legend of the Guardians: The Owls of Ga'Hoole",
  'Flight of the Phoenix',
  'Beastmaster 2: Through the Portal of Time',
  'The Chronicles of Riddick',
  'The 6th Day',
  'Rise of the Planet of the Apes',
  'The Avengers',
  'Spy Kids: All the Time in the World in 4D',
  'The Road Warrior',
  'Star Trek II: The Wrath of Khan'],
 ["Legend of the Guardians: The Owls of Ga'Hoole",
  'Flight of the Phoenix',
  'Beastmaster 2: Through the Portal of Time',
  'The Chronicles of Riddick',
  'The 6th Day',
  'Rise of the Planet of the Apes',
  'The Avengers',
  'Spy Kids: All the Time in the World in 4D',
  'The Road Warrior',
  'Star Trek II: The Wrath of Khan'])

In [56]:
import os
import pickle
moviecleaned = df

with open('moviecleaned.pkl', 'wb') as fileWriteStream:
    
    pickle.dump(moviecleaned, fileWriteStream)

    fileWriteStream.close()
    
print('pickle file is saved at Location:',os.getcwd())

pickle file is saved at Location: C:\Users\Aakash